### ISSUE TITLE
Versions: How long is maintained previous version?

### ISSUE THREAD

**Issue by Miroslav-Stopka** [shopsys/shopsys#1052]
Hi,

I've read your article https://github.com/shopsys/shopsys/blob/master/docs/contributing/backward-compatibility-promise.md. But my question is still unanswered - How long is maintained the previous version? 

I mean, for example, this PR https://github.com/shopsys/shopsys/pull/958 fixes the wrong behaviour by padding the string to an equal length with zero - thanks for this fix :). I see this fix is contained in v7.2.0.

But, seems like u didn't add this fix into v7.1.0? Did you just forget on this one? Or is it intentional = which basically means that the minor version is maintained only one month?  

**Why am I asking?**
On really big projects, upgrading to a new version - including minor upgrades - can be quite challenging and therefore very expensive. These projects will rely primarily only on bug fix updates and some bigger upgrade will be implemented once a year.

Thanks for the answer :)

**Comment by grossmannmartin** [comment]
Hi @Miroslav-Stopka,
Actually, thanks to our BC-promise, you can upgrade to 7.2 without any work (increase number in composer) and the project will work. 
You will not have the features because that would need additional work, but bugs will be fixed.

/cc @LukasHeinz

**Comment by Miroslav-Stopka** [comment]
Hi @grossmannmartin,

thank you for the quick response :)

But I'm still confused. Are you describing some "partial 7.2" upgrade? Truth is, I don't like this "partial upgrade" approach and I don't understand why there are not some REALLY minor updates containing only bug fixes.

**Comment by grossmannmartin** [comment]
Hi @Miroslav-Stopka, sorry for the delay. 
Well, I wouldn't call it a partial upgrade. To me, it's more like an upgrade of the framework without applying new features.

Patch version with only bugfixes is a good idea. We're discussing it in our team and we surely let you know, when we start releasing patch versions.

**Comment by PetrHeinz** [comment]
@Miroslav-Stopka: Please understand there is a lot of effort put into releasing a new version, mainly testing the installation on different platforms and checking for possible introduced BC breaks. Releasing patch versions for previous releases would require a lot of effort of merging branches, resolving conflicts and maintaining different branches. This would result in overall slower progress.

Don't get me wrong: I'm not saying no to releasing patch versions or releasing more often, I just wanted to point out the consequences.

As @grossmannmartin said, upgrading to a new version of packages without going through the upgrade notes will bring all bugfixes to your project. Of course, any issues fixed in the `shopsys/project-base` repository cannot be brought to you any other way than doing them yourself with the help of the upgrade notes.
Maybe we could start experimenting with [Rector](https://github.com/rectorphp/rector) to automate the process a bit.

**Comment by LukasHeinz** [comment]
Hi @Miroslav-Stopka, thanks for question: 

The basic idea is that every new feature or bug fix is targeted to the next planned minor version. If the improvement is BC break, then it goes to the major version. The general current plan is to release major versions every 3 months and minor version every month or so. 

But we realize that sometimes the project cannot be upgraded to a newer version right away. And it usually affects the upgrade for major version because it is more demanding. This is why we want to support the last minor version before the newest major release. This version will receive some bug fixes for a longer time. For example we have releases 7.2.0, 7.3.0, 8.0.0, 8.1.0. When new release (8.2.0) is approaching with an important bug fix, we will introduce a new patch version for version 7.3. The patch version will not contain all fixes, but only the ones we find important.

The second occasion we want to release patch version is when we find some severe bug (usually security vulnerability). Then we will release the patch version for the last minor version. In the previous example, this bug fix would go to patch versions of version 7.3 and 8.1. 

With our current frequent release cycle, we do not want to release a regular patch version. But we will prolong intervals between releases - currently, it is a minor version every month and major every 3 months. targeted release cycle if major version every year and minor version quarterly. In this scenario, we will add regular patch releases. 

Regarding your concerns that we will not support every minor release, I believe that upgrading to minor versions is and will be easy enough that it wouldn't be a big problem for any project. And last minor version will be supported for longer time period so the project can plan upgrades without any urgency.

I believe that I answered the main question form title and addressed all issues from the description so I will close the issue now. If you have more question or you want to add some note, please, do not hesitate and open issue once again.
