### ISSUE TITLE
Installation failed - Docker, Linux

### ISSUE THREAD

**Issue by rapemer** [shopsys/shopsys#109]
With these instructions:
https://github.com/shopsys/shopsys/blob/master/docs/installation/installation-using-docker-linux.md

I have following errors:

	E: Unable to locate package postgresql-client-9.5
	E: Couldn't find any package by glob 'postgresql-client-9.5'
	E: Couldn't find any package by regex 'postgresql-client-9.5'
	ERROR: Service 'php-fpm' failed to build: The command '/bin/sh -c apt-get update && apt-get -y install postgresql-client-9.5' returned a non-zero code: 100

Full-stack informations with command `docker-compose up -d`:

	docker-compose up -d
	Building php-fpm
	Step 1/13 : FROM phpdockerio/php72-fpm:latest
	 ---> a6e4cd6c5ef5
	Step 2/13 : ARG DEBIAN_FRONTEND=noninteractive
	 ---> Using cache
	 ---> 02b7da0918d3
	Step 3/13 : RUN apt-get update && apt-get -y install apt-utils dialog
	 ---> Using cache
	 ---> 03b67d2d4ff2
	Step 4/13 : RUN apt-get update && apt-get -y install acl
	 ---> Using cache
	 ---> 4ac99cf5c17d
	Step 5/13 : RUN apt-get update && apt-get -y install git
	 ---> Using cache
	 ---> d0f2b05ebcc7
	Step 6/13 : RUN apt-get update && apt-get -y install postgresql-client-9.5
	 ---> Running in 0b5d1daa2e14
	Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
	Get:2 http://security.ubuntu.com/ubuntu bionic-security InRelease [69.9 kB]
	Hit:3 http://ppa.launchpad.net/ondrej/php/ubuntu bionic InRelease
	Get:4 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [65.4 kB]
	Hit:5 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
	Fetched 135 kB in 1s (209 kB/s)
	Reading package lists...
	Reading package lists...
	Building dependency tree...
	Reading state information...
	E: Unable to locate package postgresql-client-9.5
	E: Couldn't find any package by glob 'postgresql-client-9.5'
	E: Couldn't find any package by regex 'postgresql-client-9.5'
	ERROR: Service 'php-fpm' failed to build: The command '/bin/sh -c apt-get update && apt-get -y install postgresql-client-9.5' returned a non-zero code: 100

**Comment by PetrHeinz** [comment]
Hello @rapemer,

thanks for reporting this issue. The issue is caused by our php-fpm image, which is based on phpdockerio/php72-fpm:latest. In the latest release there was a BC breaking change and it cannot be installed at the moment. We're already working on the solution by switching to a more stable image. You can see the WIP in https://github.com/shopsys/shopsys/compare/mc-docker-images-switch.

I will create a PR in a few hours, you're welcome to join in with comments.

There is also a hotfix https://github.com/shopsys/shopsys/commit/36df504b2fe348524a0800e7d8d7ef91587acf3e which makes the appliaction buildable, but acceptance tests fail, you can use it if you want to build the application.

**Comment by rapemer** [comment]
@PetrHeinz thanks for quick response and informations - I can wait for PR merge ;)

**Comment by MattCzerner** [comment]
Hello @rapemer,

we just commited modifications to our docker images to make it work, you can see it in this commit,
https://github.com/shopsys/shopsys/commit/013978de70f642e2909d2a7223889b5f5ac9c9b0

Please read changelog since there could be important informations for you to upgrade on new php-fpm image.

**Comment by PetrHeinz** [comment]
There were actually more changes related to changing the Docker image, see https://github.com/shopsys/shopsys/compare/c2e767dca...54408aa8b. I would advise using current `master` branch. We'll release `7.0.0-alpha2` till the end of the month.

**Comment by rapemer** [comment]
@MattCzerner, @PetrHeinz thanks, I'm going to try it ..

**Comment by rapemer** [comment]
@PetrHeinz after commands: `git checkout master` and `git pull` there is command "composer install" under `sudo` - it's very dangerous to run composer under sudo, see https://getcomposer.org/root

**Comment by rapemer** [comment]
@PetrHeinz, @MattCzerner `docker-compose up -d --build` at current `master` done without errors, thanks a lot ;)

**Comment by PetrHeinz** [comment]
@rapemer Are you sure you don't have any local custom settings of git hooks? Composer warns about executing under superuser privileges and tehere is no warning on either my machine nor on our CI.

In the image we used earlier, there was only user root, so composer was indeed run by root user (this was one of the reasons for switching the Docker image). But not using a githook.

**Comment by rapemer** [comment]
@PetrHeinz sorry, of course it's my local hook and I don't know how it could get there ..
