### ISSUE TITLE
Products - advanced search - category

### ISSUE THREAD

**Issue by PatrikBajer** [shopsys/shopsys#1103]
### What is happening
If I have a tree with a large number of categories, it happens that there are duplicates as accessories. If I try filter that products by advenced search - category and pick accessories. I don't know what accesorries Iam picking, there is no visible category hierarchy. -> http://prntscr.com/nwxkqc ; http://prntscr.com/nwxkwe

### Expected result
Show category hierarchy in advanced search for category in some way

**Comment by boris-brtan** [comment]
hi @PatrikBajer , i am not sure whether such change would be good for everyone
till then you could try to extend CategoryProductFilter from ShopBundle
https://github.com/shopsys/shopsys/compare/bb-customize-product-cat-filter

**Comment by PetrHeinz** [comment]
Hi @PatrikBajer, you're right that it can be confusing... But I'm not sure what would actually be the best behavior by default. Full category paths might be too long (example from one Czech store: *"Ložiska > kuličková miniaturní > metrická d=1 až 9mm > d : 1,2 mm > D=4 mm B=1,8 mm"*).

Maybe we could implement it in such way that when there are ambiguous names, prefix it with parent name (recursively)... See this category tree as an example:

- A
- B
  - a
  - b
    - i
    - ii
  - c
    - i
    - ii
- C
  - a
    - i
  - b
    - i
    - extra
  - c

This would then result in such labels (every label is unique and as short as possible):

- A
- B
- B > a
- B > b
- B > b > i
- b > ii
- B > c
- c > i
- c > ii
- C
- C > a
- a > i
- C > b
- C > b > i
- extra
- C > c
- d

Would that be acceptable? Maybe it would be even more confusing with some names with the prefix and some without it... Maybe instead of prefixing, we could put in in a parethesis like this:

- A
- B
- a (in B)
- b (in B)
- i (in B > b)
- ...

What do you think?

**Comment by LukasHeinz** [comment]
I see three options:

**1) Keep the whole hierarchy in one line** 

Example: 
- "Mazací technika > Komponenty pro rozvod maziva > Nástavce > Pro pákové mazací lisy"
- "Mazací technika > Komponenty pro rozvod maziva > Nástavce > Pro mazací stříkačky"
- "..."

Pro: 
- it is clear and consistent
- you really know which category you are changing

Con:
- the whole hierarchy could be too long for select box

**2) In case of ambiguous names show parent (or more):**

More info in previous [post](https://github.com/shopsys/shopsys/issues/1103#issuecomment-499527621)

Pro: 
- show parents only when necessary

Con: 
- can be confusing (sometimes there are parents, sometimes there are not)
- does not show you where this category is in tree

**3) Show whole hierarchy as a tree:**

Example: https://neofusion.github.io/hierarchy-select/

Pro:
- you really know which category you are changing

Con:
- the whole hierarchy could be too long for select box and you have to scroll


Please add more ideas or recommendations on what to use.

**Comment by PetrHeinz** [comment]
@LukasHeinz I would go for 2)

There is another con for 3) - when you try to filter the categories using search, you might get confusing structure (see https://stackoverflow.com/a/35588291). The https://neofusion.github.io/hierarchy-select/ works nicely as it always shows the parents (it even disables them if they don't match the searched text). This approach is sadly incompatible with Select2 integrated in #1241. I would rather use a single library for selectboxes.

Furthermore, I'd like to have all admin category selectboxes unified, see:
- *Category* filtering in *Advanced Search* on *Products >  Products overview*
![image](https://user-images.githubusercontent.com/10008612/62295149-b48b3380-b46c-11e9-9b81-875746f9b406.png)
- *Ancestor category* field on *Products >  Categories >  New category* (or *Editing category*)
![image](https://user-images.githubusercontent.com/10008612/62295101-9f160980-b46c-11e9-8f41-87d320e4b477.png)
- *Category* field on *Marketing >  Popular categories*
![image](https://user-images.githubusercontent.com/10008612/62295119-a806db00-b46c-11e9-91d9-3abd39100547.png)

**Comment by petrsvob** [comment]
I suggest choosing option 3) since it is clearly organized yet easy to read.

**Comment by henzigo** [comment]
Hello will be this implemented soon?

**Comment by s3tezsky** [comment]
This one was a bit improved in #1652 but still requires proper solution.

**Comment by s3tezsky** [comment]
Do not close this. It has not been implemented yet. Current state seems pretty lame a we should do something with it.

**Comment by pk16011990** [comment]
Next idea for solution: Use same category tree as in product edit form with checkboxes. Yes it is big but it is easy to implementation and consitent.
