### ISSUE TITLE
MoneyType should work with different locale

### ISSUE THREAD

**Issue by boris-brtan** [shopsys/shopsys#1184]
### What is happening

If we have set locale that contains decimal_separator comma instead of dot, Money functionality starts to fail.
### Expected result

Money will work also with different locale set

**Comment by boris-brtan** [comment]
hi @vitek-rostislav, i got info that @pk16011990 noticed maybe some related issue with setting in Bootstrap.php where we force set the LC_LOCALE

**Comment by pk16011990** [comment]
Yes, SSFW forces locale `setlocale(LC_CTYPE, 'en_US.utf8');` but not for numbers. When server has different locale (eg. czech), priority tag in sitemap containts decimal number with invalid formating (decimal separator is `,` instead of `.`)

I suggest to add `setlocale(LC_NUMERIC, 'en_US.utf8');` (or `LC_ALL`?) into `Bootstrap.php` and add test how is decimal number formatted eg. via `sprintf()` (it is used in sitemap generation)
