### ISSUE TITLE
Referer does not work after administrator login

### ISSUE THREAD

**Issue by pk16011990** [shopsys/shopsys#1316]
### What is happening
Use-case: I'm on product detail page in administration. Somehow I get logged out (login from another place, sessions expired...). So, I log in again but I'm redirected to dashboard but not to the page where I was before...

It worked in the past...

### Expected result
Administrator is redirected onto referer after login.

**Comment by s3tezsky** [comment]
Hi @pk16011990 , could you please specify in which version it is happening?

I have just tried it in actual _master_ and this issue seems to be invalid. Everything is working just fine (removing session id cookie, logging in from other place, even when wrong credentials are filled at first time). Everytime I got to page when I were before. Even when I e.g. click (when session expired) from Products to Orders after logging in it redirects me to Orders fine as well.

**Comment by pk16011990** [comment]
Hi,

I tried it again and It works...after remove session id cooki, logging in from other place etc... However It does not work after restart docker containers. 

Example:

I'm on url `http://127.0.0.1:8000/admin/product/edit/72`, restart containers by:
```bash
docker-compose down && docker-compose up -d --build
```
Refresh page (or click on some link), I'm redirect to login page and after login I'm on `http://127.0.0.1:8000/admin/dashboard/` not on `http://127.0.0.1:8000/admin/product/edit/72`.

Yes, I understand it is edgecase and only during developing, but I work with more eshops in SSFW and it is little annoying. However, I do not know if it has a fancy solution, so I would learn to live with it in development environment.

**Comment by grossmannmartin** [comment]
I think it's because the previous url is taken from HTTP_REFERER header (see \Symfony\Component\Security\Http\Authentication\DefaultAuthenticationSuccessHandler:#L115)
And when you restart the container, this header is lost. 
I don't think this has some neat solution.
