### ISSUE TITLE
PromoCodes and OrderRounding are OrderItems with type product

### ISSUE THREAD

**Issue by DavidOstrozlik** [shopsys/shopsys#1390]
### What is happening

Promo codes and order rounding are OrderItems with type "product" which doesn't really makes sense as they're not products but behave like it.

### Expected result

Maybe it would be better to have new types of order items for promo codes and order rounding so we don't use type product for everything.
I would be glad to hear more ideas how to solve this or if it would make sense to do this at all.

**Comment by sspooky13** [comment]
@henzigo or someone, can you add for this and https://github.com/shopsys/shopsys/issues/1263 add label "Status: in implementation" because it exists PR for these issues, please?

P.S.: can you edit PR https://github.com/shopsys/shopsys/pull/1563 "Fixes issues" row to "closes #1390, closes #1263"?

thanks

**Comment by pk16011990** [comment]
It's related with https://github.com/shopsys/shopsys/pull/1563 and I should be resolved in this PR. -> I'm closing this issue as a duplicate.
