### ISSUE TITLE
native install "Symfony initialization" too long

### ISSUE THREAD

**Issue by jan-oliva** [shopsys/shopsys#1398]
**Shopsys version 8.0.0.**
The same problem is on 7.0.0.

On native installation "**Symfony initialization**" too long (**1500 ms**)   in symfony debug bar. 

Other symfony apps (sylius) on the same server has "Symfony initialization" about 40ms.  

Shopsys 8.0.0 on docker has "**Symfony initialization**" about **75ms**. 

I found diference between doker and native instalation that native install use shopsys libs from packages dir and docker install from vendor, can be locationof shosys libs reason for slow "Symfony initialization" ?

I tried composer install in project-base as docker version, but some Classes from vendor unable load, because autoloader try ti find vendor from root directory, instead of project-base/vendor.
For example commerceguys/intl/src/NumberFormat/NumberFormat, try to load from root_dir/vendor and root_dir/vendor not exists.

When run composer install from root_dir, project works, but very slowly  "**Symfony initialization**" about 1500ms and more.

https://retezy-vam-com-dev.pixeldesign.cz/_profiler/0c3c46?panel=time

**Total execution time - 3226 ms**
**Symfony initialization - 2990 ms**

**Comment by henzigo** [comment]
Hello, 
first of all, you are using `framework development` version instead of `project-base` which you should use to implement your project. 

With installed correctly version for your project, you should never have any `package/*` folders. [See](https://github.com/shopsys/shopsys/blob/master/docs/installation/native-installation.md#create-new-project-from-shopsys-framework-sources)
 
Another thing is that Symfony debug bar slowing page rendering, so if you will disable it you will get better performance. 

Please try to install correct version via `composer create-project shopsys/project-base --keep-vcs` and let me know if your project is still slow.

**Comment by hacfi** [comment]
@jan-oliva Are you running Docker on Windows or Mac? If so the long load time is due to the slow file synchronisation.

**Comment by grossmannmartin** [comment]
Hi, @jan-oliva,
any progress on this issue?

**Comment by jan-oliva** [comment]
Hi, no any progress with this problem. I was very bussy to solve it. Production Shop was started on VPS, but is slowly than my notebook with docker version :(
Production run on 2 VPS DB and APP, on the same HW. Viz https://github.com/shopsys/shopsys/issues/1398#issuecomment-530792063
Ping between servers is cca 600 micro sec. Both servers use SSD HDD, both use DNS cache. CPU Load  nearly 0, RAM usage about 15%. Both servers are bored. But HTTP response (with test data and empty DB) on nginx are 1 - 3.5 sec .

Testing shop on Sylius on the same VPS servers and php version has HTTP responses about 300-600 ms. Difference between cases is DB, sylius uses Mysql and Shopsys postgres on the same VPS DB server
