### ISSUE TITLE
Newsletter subscription in footer result in 404 on second submit

### ISSUE THREAD

**Issue by grossmannmartin** [shopsys/shopsys#1404]
### What is happening
Submitting `\\@shoh.co` as an email address in newsletter subscription form in the footer first-time show warning exclamation mark from server validation, which is good.

![Snímek obrazovky 2019-09-13 v 11 39 52](https://user-images.githubusercontent.com/1177414/64853374-88da9c00-d61b-11e9-84a0-7e6e78a5e2f8.png)

But submitting the form again (without any change) results in page reload and 404 page.

_may be somehow related with #747_

### Expected result
404 page should not be raised in this case.

**Comment by sspooky13** [comment]
I want only add info:
that error is also in "contact us" form.
![obrázok](https://user-images.githubusercontent.com/25614491/67547292-fb509880-f6fe-11e9-8eeb-80817ad8bf19.png)

and 404, because second time form is sent without AJAX so browser go to URL which is allowed only as POST request
![obrázok](https://user-images.githubusercontent.com/25614491/67547381-3d79da00-f6ff-11e9-973f-09bd02f0ddd2.png)
![obrázok](https://user-images.githubusercontent.com/25614491/67547395-45397e80-f6ff-11e9-962b-21f9af97795d.png)

I think it is error in javascript but no one error message showing after second click to form 😐 maybe `packages/framework/src/Resources/scripts/common/validation/customizeBundle.js`? 🤔

**Comment by pk16011990** [comment]
I can not reproduce it. Is it still there?

**Comment by grossmannmartin** [comment]
already resolved
