### ISSUE TITLE
Javascripts in one file and minify content

### ISSUE THREAD

**Issue by jakubhavlak** [shopsys/shopsys#201]
Our customers have request on minify of javascript code. I implemented this request on one project and i would like it to share. Code watch, whether enviroment is not development, then minify code and create javascript version file to cache folder. If javascript version file in cache folder exists, load a javascript by version. History is not good. If you know how it to rewrite better, i will a glad.

Thank you for approve this.

Merge request can be faound on:
https://git.shopsys-framework.com/shopsys/shopsys-framework/merge_requests/10

**Comment by LukasHeinz** [comment]
Original comment by @sustmi :

Hi Peter.

Thanks for your merge request. From a brief look on the code I have a suspicion that it does not handle stores with multiple languages correctly. Here: !10 (diffs) you can see that when file with the version exists, the output file is not generated. Now, if you clear all generated files and go to english domain the code will generate version file and english JavaScript files. Then you go to german domain and your code will try to return assets/scripts/de/something-<version>.js that does not exist because only en version is generated.

Am I right? (Clarification: I did not actually run the code and test the scenario.)

However, we will probably rewrite the functionality from scratch anyway so you do not have to fix it in this merge request.
.
.
.
I tried to come up with some cleaner solution for combing JavaScripts while keeping all existing features of JavaScript compilation.
I was wondering whether we can use some existent solution and no reinvent the wheel. I tried both Webpack Encore and Assetic but none of them fulfilled all the needs.

## Trying Webpack Encore
I installed Webpack Encore (https://symfony.com/doc/3.4/frontend/encore/installation.html) and used the following configuration:
```js
// webpack.config.js
var Encore = require('@symfony/webpack-encore');

Encore
    // the project directory where all compiled assets will be stored
    .setOutputPath('web/build/')

    // the public path used by the web server to access the previous directory
    .setPublicPath('/build')

    .addEntry('frontend', './src/Shopsys/ShopBundle/Resources/scripts/frontend/app.js')

    .createSharedEntry('vendor', [
        'jquery'
    ])

    // allow legacy applications to use $/jQuery as a global variable
    .autoProvidejQuery()

    .enableSourceMaps(!Encore.isProduction())

    // empty the outputPath dir before each build
    .cleanupOutputBeforeBuild()
;

// export the final configuration
module.exports = Encore.getWebpackConfig();
```

The `Resources/scripts/frontend/app.js` file looked like this (I did expand all the wildcards yet):
```js
require('../../../../../../web/bundles/bmatznerjqueryui/js/minified/jquery-ui.min.js')
require('./components/escape.js')
require('./components/keyCodes.js')
require('./register.js')
require('../../../../../../web/bundles/fpjsformvalidator/js/fp_js_validator.js')
require('./bootstrap/tooltip.js')
require('./bootstrap/popover.js')
//require('./plugins/*.js')
require('./plugins/slick.js')
//require('./validation/form/*.js')
//require('./validation/*.js')
//require('./cart/*.js')
//require('./order/*.js')
//require('./product/*.js')
//require('./*.js')
require('./slickInit.js')
//require('./components/*.js')
```

### The problems I ran into with Webpack:
* We compile JavaScript files using PHP class `\Shopsys\ShopBundle\Component\Javascript\Compiler\JsCompiler` that replaces translations and PHP constants. It would be hard to implement the feature in pure JavaScript. However, this could be solved by creating custom Webpack plugin (something like https://webpack.js.org/plugins/uglifyjs-webpack-plugin/) that would run a PHP script through CLI to compile the JavaScripts.
* We have separate output JavaScript files for each domain locale. I do not know how to solve this in Webpack.
* Webpack does not support wildcard inclusion of files (eg. `frontend/plugins/*.js`).
* Webpack is slow in dev environment with `--watch` argument when you want to compile all the JavaScripts on-the-fly. It takes more than 5 seconds (and I did not even include all the files yet).

## Trying Assetic
I tried using Assetic with the following configuration:
```yaml
# app/config/config.yml
assetic:
  debug: "%kernel.debug%"
  use_controller: false
  bundles: [ShopsysShopBundle]

  variables:
    locale: ['cs', 'en']
  workers:
    cache_busting:
      enabled: true
```

Then I changed the `<head>` section in the layout file to contain this:
```twig
{% javascripts
    output='assets/scripts/frontend/combined_{locale}.js'
    vars=['locale']
    '@BmatznerJQueryBundle/Resources/public/js/jquery.min.js'
    '@BmatznerJQueryBundle/Resources/public/js/jquery-migrate.js'
    '@BmatznerJQueryUIBundle/Resources/public/js/minified/jquery-ui.min.js'
    '@ShopsysShopBundle/Resources/scripts/frontend/components/escape.js'
    '@ShopsysShopBundle/Resources/scripts/frontend/components/keyCodes.js'
    '@ShopsysShopBundle/Resources/scripts/frontend/register.js'
    '@FpJsFormValidatorBundle/Resources/public/js/FpJsFormValidator.js'
    '@ShopsysShopBundle/Resources/scripts/frontend/bootstrap/tooltip.js'
    '@ShopsysShopBundle/Resources/scripts/frontend/bootstrap/popover.js'
    '@ShopsysShopBundle/Resources/scripts/frontend/plugins/*.js'
    '@ShopsysShopBundle/Resources/scripts/frontend/validation/form/*.js'
    '@ShopsysShopBundle/Resources/scripts/frontend/validation/*.js'
    '@ShopsysShopBundle/Resources/scripts/frontend/cart/*.js'
    '@ShopsysShopBundle/Resources/scripts/frontend/order/*.js'
    '@ShopsysShopBundle/Resources/scripts/frontend/product/*.js'
    '@ShopsysShopBundle/Resources/scripts/frontend/*.js'
    '@ShopsysShopBundle/Resources/scripts/frontend/components/*.js'
%}
		<script src="{{ asset_url }}"></script>
{% endjavascripts %}
```

### The problems I ran into with Assetic:
* Assetic has some strange bug that causes that `bin/console assetic:dump` command dumps contents to a file named `web/assets/scripts/frontend/combined-885dd1c_popover_9-0a0f608.js` (note that two cache busting versions are included) but in `<head>` section of the page the URL points to `/assets/scripts/frontend/combined_popover_9-0a0f608.js` (note that there is not the `885dd1c` version hash in the URL). This causes browser to try to download a non-existent file.
* The version hash in file name is included in the cached Twig file even in development environment. That means that when you change source JavaScript `bin/console assetic:watch` command creates new generated file but when you reload the page the URL in `<head>`  section points to the old file until you clear the Twig cache.

## Conclusion
We need to create a custom solution for combining and minification of the files that satisfies all our needs:
* files from within `admin` and `frontend` directories are compiled using `\Shopsys\ShopBundle\Component\Javascript\Compiler\JsCompiler` (replacing translation messages and PHP constants)
* wildcards in paths are supported
* different files are generated for each domain locale
* in development environment, files are recompiled automatically and it takes reasonable time (ideally less than a second)
* in development environment it is possible to locate the source JavaScript file in case of runtime error in browser (note: [source maps](https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Use_a_source_map) look cool)
* in production environment, files are combined into one
* in production environment, compilation process is run only once (not with every request) so that it does not load IO and CPU

@peter.turek: Thank you again for your merge request. However it solves the problem for your project we need to refactor the code significantly to be suitable for merging into upstream of Shopsys Framework. The `JavascriptCompilerService` is already violating SRP and we do not want to clutter it with any more responsibilities. This rewrite will take a while.

**Comment by pk16011990** [comment]
Reopen. I like and want this feature :)

**Comment by LukasHeinz** [comment]
StaleBot, please open this issue. I want it to be resolved. Thank you

**Comment by pk16011990** [comment]
remove stale label...

**Comment by sspooky13** [comment]
Hello,
I want to ask question: What it looks like with this feature/enhancement? 🤔
I develop (again something) bundle which should add this feature to symfony project. But if you tell me this feature is in progress so I will not hurry with bundle and I won't offer it to you.

Thanks for info.

**Comment by LukasHeinz** [comment]
Since September we will have a new person responsible for front-end technologies, so we will decide how to tackle this issue. Moreover, the initial report about problems with Webopack is more than one year old so maybe Webpack will solve it all...

I believe that we will have a decision about progress until the end of September

**Comment by sspooky13** [comment]
Hello @LukasHeinz,
thanks for the reply. I understand it. So I don't hurry to finish my bundle. 👍

**Comment by henzigo** [comment]
Hey stale bot, there is some progress #1545

**Comment by pesektomas** [comment]
Hello, thx @henzigo for ping me this issue. In #1545 we rewrited javascripts to classes and use webpack encore as asset managment. We have some points in first comment and I want to comment it.

* We compile JavaScript files using PHP class - it is overkill, we deleted it. We used constants as constants (in separated file and we can open discussion about it) and we used translations as separated file. We created script, which find all call of trans (or transchoice) method and for these translation strings find translations in po files. This script is in webpack event hook, so nobody have to manually run exporting  translations (fyi: for finding call methods is used @babel/parser and @babel/traverse).

* We have separate output JavaScript files for each domain locale. I do not know how to solve this in Webpack. - I think that we dont need load javascripts per domain

* Webpack does not support wildcard inclusion of files (eg. frontend/plugins/*.js) -  it is true, but we moved all plugins into npm package manager and for other folders we created index.js files who include individually scripts. We want total controll about included scripts.


* Webpack is slow in dev environment with --watch argument when you want to compile all the JavaScripts on-the-fly. It takes more than 5 seconds (and I did not even include all the files yet). - complet build takes 3413ms, when I run watch command, watch for changes takes 273ms. (ofcourse when I have installed all npm dependencies).

And more points:

* in development environment it is possible to locate the source JavaScript file in case of runtime error in browser (note: source maps look cool) - yes, we used source maps

* in production environment, files are combined into one - not completely. We create two files (frontend.js and frontend_nodes.js). In future we can split files to homepage.js, product.js, cart.js or order.js - it is very simple to split frontend javascripts.

* in production environment, compilation process is run only once (not with every request) so that it does not load IO and CPU - yes, javascrcipts are build on ci
