### ISSUE TITLE
Inconsistency of form data in controllers

### ISSUE THREAD

**Issue by jakubhavlak** [shopsys/shopsys#209]
Issue#30 Inconsistency of form data in controllers
https://git.shopsys-framework.com/shopsys/shopsys-framework/issues/30

I noticed in admin controllers has inconsistency getting of form data. In edit action, data is sended direct to facade but in new action, data is extracted to variable and only then data is sended to facade. If you notice, for example, in: AdvertController:

https://git.shopsys-framework.com/shopsys/shopsys-framework/blob/master/src/Shopsys/ShopBundle/Controller/Admin/AdvertController.php#L78-87
https://git.shopsys-framework.com/shopsys/shopsys-framework/blob/master/src/Shopsys/ShopBundle/Controller/Admin/AdvertController.php#L173-182 ArticleController:
https://git.shopsys-framework.com/shopsys/shopsys-framework/blob/master/src/Shopsys/ShopBundle/Controller/Admin/ArticleController.php#L93-102
https://git.shopsys-framework.com/shopsys/shopsys-framework/blob/master/src/Shopsys/ShopBundle/Controller/Admin/ArticleController.php#L93-102 etc.

I found, that process do to same. I mean, it could be unified.
Thank you for approve this.

**Comment by sspooky13** [comment]
Hello Mr. @Miroslav-Stopka,

How good you personally ask me for help because I did not want to do it 😄
To answer your question, i write for you a few place where is still usage inconsistent:

https://github.com/shopsys/shopsys/blob/87c13b9be7e4999a424a43711ab78e2879d2257b/packages/framework/src/Controller/Admin/VatController.php#L149
https://github.com/shopsys/shopsys/blob/87c13b9be7e4999a424a43711ab78e2879d2257b/packages/framework/src/Controller/Admin/UnitController.php#L155
https://github.com/shopsys/shopsys/blob/87c13b9be7e4999a424a43711ab78e2879d2257b/packages/framework/src/Controller/Admin/TransportController.php#L70
https://github.com/shopsys/shopsys/blob/master/packages/framework/src/Controller/Admin/TransportAndPaymentController.php#L61

I apologize, but I have not written all the places where it is because they are little bit more.
If you don't understand what i mean i will be glad when i contact me personally because this write communication taking too long.

Thank you for understanding

**Comment by Miroslav-Stopka** [comment]
So, basically, the problem is the inconsistency between editAction and newAction in some controllers. For example `ArticleController` contains editAction in which the data object `$articleData` is filled by method `handleRequest`:

```
       $form = $this->createForm(ArticleFormType::class, $articleData, [
            'article' => $article,
            'domain_id' => $this->adminDomainTabsFacade->getSelectedDomainId(),
        ]);
        $form->handleRequest($request);
```

but in newAction, there is also row `$articleData = $form->getData();` wich is propably unecessary. 

Thank you @sspooky13 for consultation, I will check it soon :)
