### ISSUE TITLE
Translated text extraction from custom validation

### ISSUE THREAD

**Issue by jakubhavlak** [shopsys/shopsys#218]
Some buzzwords that are being translated are not currently being extracted from the source and therefore not translated.

Currently:

- public attributes for Symfony \ Component \ Validator \ Constraint Symfony, eg SS6 \ ShopBundle \ Component \ Constraints \ UniqueSlugsOnDomains

- call addViolation on the \ Symfony \ Component \ Validator \ ExecutionContextInterface object with a specific string as an argument, such as SS6 \ ShopBundle \ Form \ Front \ Order \
TransportAndPaymentFormType ::validateTransportPaymentRelation (deprecated, it would have been a buildViolation call on Symfony \ Component \ Validator \ Context \ ExecutionContextInterface)

We have an idea about to extract all public attributes ending in the message (requiring renaming UniqueSlugsOnDomains :: $ messageDuplicate) classes inheriting Constraint and all calls to the addViolation / buildViolation method on any object if the string literal (or concatenation) is given as the first argument.

We have not addressed it at this time because the messages are not used (most of the messages are transcribed by another, more specific, or replaced by another validator in JS validation). In the worst case scenario, an English message will appear on the FE in another language, which will still be understood by most people.

**Comment by pk16011990** [comment]
ping (prevent stale)

**Comment by PetrHeinz** [comment]
The calls to `addViolation` are automatically extracted since #448 was merged.

Public attributes called `$message` of `\Symfony\Component\Validator\Constraint` sub-classes are not extracted yet. 

There is also public attribute called `$messageDuplicate` in `\Shopsys\FrameworkBundle\Form\Constraints\UniqueSlugsOnDomains` - should this be also extracted? This would be inconsistent with the behavior of `\Shopsys\FrameworkBundle\Component\Translation\ConstraintMessageExtractor`, that expects all option keys for messages are ending "message" (case-insensitive). What do you think, @pk16011990?

**Comment by PetrHeinz** [comment]
@pk16011990: I've tried to quickly come up with a possible solution in #564, can you take a look at it? It seemed to me that it would be more effective to discuss it above a working piece of code.

**Comment by pk16011990** [comment]
#448 and new #564 look great! #564 solves this problem - I think. 

Problem with `UniqueSlugsOnDomains` it problem in this class with inconsistency, but solution is very easy. Extracting translation from `UniqueSlugsOnDomains` without #564 is very frustrating.

Thanks!
