### ISSUE TITLE
Correction of generated icon documentation

### ISSUE THREAD

**Issue by jakubhavlak** [shopsys/shopsys#220]
If I open the docs/generated/webfont-admin-svg.html:

- Firefox probably does not load the font (Unicode code squares are displayed)
- Chrome does not work on scale: 1.5 on hover - icon disappears

**Comment by kulincz** [comment]
There is more information about this issue: https://stackoverflow.com/questions/2856502/css-font-face-not-working-with-firefox-but-working-with-chrome-and-ie
I was try that first solution and it works ... but the problem is that solution depends on local firefox browser settings ... in HTML file we linking local files and it is against default privacy policy of firefox browser. I can't see solution for this now.

**Comment by kulincz** [comment]
I tried it now and it works in chrome (68), safari and firefox (61) .. so maybe it's fixed itself, what do you think? :-)

**Comment by LukasHeinz** [comment]
@TomasLudvik, you upvoted this issue. Can you please check if it is still relevant? Thanks

**Comment by TomasLudvik** [comment]
I do not know how this works nor what should I test. I upvoted it because in the description it seemed important to me. Please do not make some dependencies via voting ;)

Btw: I opened docs/generated/webfont-admin-svg.html and I got 404...
