### ISSUE TITLE
Drop symplify/* dependencies 

### ISSUE THREAD

**Issue by grossmannmartin** [shopsys/shopsys#2209]
## Describe the expected outcome of your requested feature
Symplify packages do not have a clear support policy and break semver occasionaly, which makes maintenance of the application unnecessarily hard sometimes.

New versions are incompatible with our dependencies. 

I would like to remove all usages of symplify classes from the code and use only `-prefixed` versions of the required tools (for example https://github.com/symplify/easy-coding-standard-prefixed)

### Is your feature request related to a problem?
symplify/symplify#2872

**Comment by TomasLudvik** [comment]
First of all - I was shocked from how short support of ECS versions is and even what reaction we got in the issue. Our version is from May 2020 and newer version with 8, got its last patch in end of October and is also no longer supported. People are even using versions 6 and maybe even older and get absolutely no help from authors. 

If I move over, because it is open source and people can do whatever they want with theirs projects, I looked at that prefixed version and found only info "use this, if you have problems with dependencies". Do we have some more info about it? How did they do that? Is it guaranteed it will work?

My trust in Symplify is degrading over last few years as this is not first case we had to solve promptly problems caused by it with almost no help from authors and such problems affect even our customers and community. 

This leads me to one thought - maybe we should abandon Symplify and find some other solution with better and long term support?
