### ISSUE TITLE
Docker build is not working

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#238]
### What is happening
When trying to build the application using `docker-compose up -d --force-recreate --build` after I removed my cached containers (using `docker rmi $(docker ps)`), I got an error:
```
ERROR: unsatisfiable constraints:
  postgresql-10.4-r0:
    breaks: world[postgresql<9.6]
ERROR: Service 'php-fpm' failed to build: The command '/bin/sh -c apk add --update --no-cache --repository https://dl-cdn.alpinelinux.org/alpine/v3.4/main "postgresql<9.6"' returned a non-zero code: 1
```
I thought that it was fixed in https://github.com/shopsys/shopsys/pull/229 but it seems there is yet another problem :slightly_frowning_face: 

### Expected result
The Docker build passes.

**Comment by PetrHeinz** [comment]
Command `docker rmi $(docker ps)` doesn't work for me - it feed full list of currently running containers to the removal of images. But I've duplicated your problem with this approach:
```bash
# I've stopped all my running containers
docker stop $(docker ps -q)
# I've removed all my containers
docker rm $(docker ps -q -a)
# Then I've force-removed all my images
docker rmi $(docker image ls -q)
# After I have cleared everything I could think of, I've run just
docker-compose up -d
```
The underlaying problem was mentioned a few lines above in the console log:
```
 ---> Running in e8a67f035559
fetch https://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
SSL certificate subject doesn't match host dl-cdn.alpinelinux.org
fetch https://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.4/main: Permission denied
SSL certificate subject doesn't match host dl-cdn.alpinelinux.org
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz: Permission denied
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  postgresql-10.4-r0:
    breaks: world[postgresql<9.6]
ERROR: Service 'php-fpm' failed to build: The command '/bin/sh -c apk add --update --no-cache --repository https://dl-cdn.alpinelinux.org/alpine/v3.4/main "postgresql<9.6"' returned a non-zero code: 1
```
It seems that dl-cdn.alpinelinux.org doesn't have a valid SSL certificate, but the original dl-3.alpinelinux.org does. In the list of mirrors on https://dl-3.alpinelinux.org/alpine/ and in the rest of our build there are only http:// addresses, that's why it slipped my mind when doing #229. What confuses me is that I've managed to build the container yesterday...

If I drop the usage of https in the Dockerfile, the build finishes fine. As the build already fetches from dl-cdn.alpinelinux.org without SSL, I can't see any negative consequences with this change, please, see #241. It might still be worth the time investigating further and maybe thinking about ensuring the security and stability of the Docker image builds...

**Comment by MattCzerner** [comment]
Fixed in https://github.com/shopsys/shopsys/commit/f9c89995b7284899de28885cd25f05c5f538f1b8.

User story was created for storing images on docker hub and making sure to always deliver functional image for containers
