### ISSUE TITLE
monorepo-tools: Copying over history from older repositories

### ISSUE THREAD

**Issue by jakeleventhal** [shopsys/shopsys#250]
### What is happening
When copying over multiple repositories, only the first has all of the branches (expected result). However, I expected the history of the other repositories to be copied as well. Running the load script doesn't achieve this goal.

### Expected result
After running monorepo_build.sh, the sub repositories, despite not having branches, should still have all of their histories.

**Comment by PetrHeinz** [comment]
Hello Jake,

I'm not exactly sure what you mean by having history. This is how it works: 

Let's suppose we have two repositories *alpha* and *beta*, each with master branch and one other branch. Alpha looks like this with commits marked as `A0` - `A3`:
```
* A2 (master)
* A1
|
| * A3 (branch)
|/
* A0
```
Repository *beta* looks like this with commits `B0` - `B3`:
```
* B1 (master)
|
| * B3 (branch)
| * B2
|/
* B0
```
After building a monorepo via `monorepo_build.sh alpha beta` it will merge both repositories and move all their files indo directories */alpha/* and */beta/*. There will be commits `A'0` - `A'3` and `B'0` - `B'1`, the apostrophe (') marking the change of directory structure (eg. commit `A'0` is `A0` with all changes made in directory */alpha/*) and one merge commit `M`:
```
* M (master)
|\
| * B'1
| * B'0
|
* A'2
* A'1
|
| * A'3 (branch)
|/
* A'0
```
History of both repostories will be preserved, but there will be no files of repostory *alpha* in `B'0` - `B'1` nor any files of repostiry *beta* in `A'0` - `A'3` because they are before the two repositories were merged.

Does that answer your question? Can you maybe explain what are you trying to achieve more clearly?
