### ISSUE TITLE
[Insight] Interfaces names should end with Interface - in Smoke tests

### ISSUE THREAD

**Issue by LukasHeinz** [shopsys/shopsys#332]
**[in packages/http-smoke-testing/src/RequestDataSetConfig.php, line 7](https://github.com/shopsys/shopsys/blob/f0212bec7fa7d1ae1ce1b5e5feb78b3b4593dc11/packages/http-smoke-testing/src/RequestDataSetConfig.php#L7)**

> Interface `RequestDataSetConfig` should be named `RequestDataSetConfigInterface` for better clarity.

```php

namespace Shopsys\HttpSmokeTesting;

use Shopsys\HttpSmokeTesting\Auth\AuthInterface;

interface RequestDataSetConfig
{
    /**
     * Sets an authentication method and parameters via an AuthInterface implementation.
     *
     * @see \Shopsys\HttpSmokeTesting\Auth\BasicHttpAuth
```

**[in packages/http-smoke-testing/src/RouteConfig.php, line 5](https://github.com/shopsys/shopsys/blob/f0212bec7fa7d1ae1ce1b5e5feb78b3b4593dc11/packages/http-smoke-testing/src/RouteConfig.php#L5)**

> Interface `RouteConfig` should be named `RouteConfigInterface` for better clarity.

```php
<?php

namespace Shopsys\HttpSmokeTesting;

interface RouteConfig
{
    /**
     * Skips this route completely. Debug notes will be shown only when executing PHPUnit in verbose mode.
     *
     * @param string|null $debugNote
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/3b647b6b-ff37-406c-ae0a-e004328ef47f/analyses/1?status=violations)_

**Comment by LukasHeinz** [comment]
This is output from SensioLabs Insight and it is only suggestion. Please consider it.

**Comment by MattCzerner** [comment]
After consulation with @PetrHeinz and @vitek-rostislav we came to this conclussion:

We dont have any rule or sniff for controlling it and we currently have Exception interfaces which are not named with `Interface` postfix. We are not currently sure if we want to rename all this exceptions that way and we are not even 100% sure that we want to name all of these interfaces with postfix.

Long story short, we dont want to solve this issue now without implementing a sniff for it. Because of that, Issue will be closed for now.
