### ISSUE TITLE
Plugins should not add cron modules automatically into application

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#350]
### What is happening
*Reported by @jDolba*.
It is very weird that a plugin can register new cron module simply by tagging a service with `shopsys.cron` tag (and implementing the cron module interface). This might be bad for at least two reasons:
- any bundle can add cron module into application and a developer might not even notice it
- the plugin's cron modules are run with higher priority that those that are defined in `ShopsysFrameworkBundle` and `ShopsysShopBundle` (as these bundles are loaded last) and a developer is not able to influence the order of cron modules.

Note: You can see order of cron modules along with launch times by adding following code into `\Shopsys\ShopBundle\Component\Cron\Config\CronConfig::getCronModuleConfigsByTime()`
```
d(array_map(function(CronModuleConfig $config) {return $config->getServiceId() . $config->getTimeHours() . $config->getTimeMinutes();}, $this->cronModuleConfigs));
exit;
```

### Expected result
A developer has the definite power over cron modules in his application (i.e. is able to enable/disable a cron module, change their order or time of execution easily) - inlcuding cron modules installed by external bundles.

**Comment by PetrHeinz** [comment]
A developer already has this power, he can enable or disable modules by overwriting the service definition.

**Comment by jDolba** [comment]
1. cron modules registered from other bundles are always first in priority of execution, ShopsysBundle modules are always after that, I think this is wrong only by definition

2. only way how to solve 1) is override this service - untag "cron", create new service ID with same class and move it on proper "position" in cron modules list to redefine priority. 

responsible developer should do this with all cron modules registered as plugins to have this "definite power"

**Comment by PetrHeinz** [comment]
If the order of execution is a concern, maybe a priority as a part of the
shopsys.cron_module tag should be implemented.



[image: Logo Shopsys] <https://www.shopsys.com/>
[image: Foto]


*PetrHeinz*

*Full-Stack Developer*
[image: Mobil] +420 595 177 105 <+420595177105>
[image: Email] petr.heinz@shopsys.com
[image: Email] www.linkedin.com/in/petr-heinz
[image: www] www.shopsys.com


2018-07-27 9:13 GMT+02:00 Jakub Dolba <notifications@github.com>:

**Comment by jDolba** [comment]
I like simple things, one file with definition of all cron modules and their order/priority is pretty straight forward for me and solves all my problems with current cron-modules settings especially if you consider issue #356 
Imagine there are cron-services defined in many files, with any priority tag value + with some cron instance name...happy debugging

**Comment by grossmannmartin** [comment]
ping

**Comment by pk16011990** [comment]
ping (prevent stale)

**Comment by henzigo** [comment]
ping

**Comment by henzigo** [comment]
Hello @TomasLudvik, I do not think that your PR solved this issue because you are still able to declare your cron via `shopsys.cron` in external bundle, like PohodaBundle.

**Comment by TomasLudvik** [comment]
Hello @henzigo, yes you are right about that part. I have discussed this with @pk16011990 and we came to an agreement, that the main problem here was, that managing crons was possible, but a little bit difficult. That is why we moved all definitions to project-base (even the one you are mentioning) so developers can easily manage them.

We want to keep the ability to add crons from other places in order to be able to add new features in the future without the necessity to create a BC-break.

Thank you for opening this discussion, so it will be more clear for others.

**Comment by henzigo** [comment]
But I do not agree with that. As project implementator, we should have control over crons, but I'm afraid that any bundle can register any cron without we will know that. 

I like that you discussed this with @pk16011990, but probably you should discuss it here with @vitek-rostislav and @jDolba.

I'm reopening this issue because for me it's not fully resolved. Thanks for understanding.
