### ISSUE TITLE
Inconsistent annotations of constructors

### ISSUE THREAD

**Issue by MattCzerner** [shopsys/shopsys#376]
### What is happening
Right now in our application there is inconsistency in our `__construct` methods. Sometimes we do not write annotations and sometimes we do.

### Expected result
There is decision on if we want to write or do not want to write annotations to constructors and annotations are changed on this decision

**Comment by PetrHeinz** [comment]
The original idea was that we do write annotation above every method except actions in controllers and constructors of services if all argument are type-hinted (and therefore autowired). This was before we begun to use scalar type-hinting.

This approach was chosen mainly because of missing scalar type-hints and missing support in IDEs. Both these issues are now solved so we can change the rules (and, ideally, enforce them via sniff)

**Comment by Miroslav-Stopka** [comment]
Hi @MattCzerner,
seems like that this problem will not be the easy pick :). We have decided to solve this problem somewhat systematically. We need to explore it more deeply and decide how we want to work with annotations and, in fact, with the type hints. We have already assigned this problem to our backlog and will be working on it in the near future. We'll keep you informed :)

**Comment by Miroslav-Stopka** [comment]
Hi @MattCzerner,

I have some news for you :) We discussed it with several developers, and we decided to annotate everything. This is the most standard way, and at the same time makes the annotation clear and consistent. Problem will be solved in #417. I'm closing this issue.
