### ISSUE TITLE
http-smoke-testing - very high memory usage

### ISSUE THREAD

**Issue by wuestkamp** [shopsys/shopsys#418]
Hi,

we are checking like 200+ routes using the shopsys/http-smoke-testing which leads to memory usage of up to 4GB! Is this because of the phpunit DataProvider is used in the HttpSmokeTestCase? Is there a way we can prevent this?

Thanks,
Kim

**Comment by vitek-rostislav** [comment]
Hi @kimwue! Thanks for reporting the issue, I'll try to investigate it today and let you know :+1:

**Comment by vitek-rostislav** [comment]
Hi there again, just to let you know, sadly, I did not get to it today, so hopefully tomorrow :slightly_smiling_face:

**Comment by kimwue** [comment]
Thanks a lot for fast testing, I will check the points you made soon. For a current workaround I use `phpunit --process-isolation`.

**Comment by PetrHeinz** [comment]
Hi @wuestkamp, any luck finding out what in which use cases is the memory usage so high?

**Comment by wuestkamp** [comment]
I haven't had time yet to dive deeper into it. But thanks for checking this thoroughly and confirming that it must be an issue with our application. Closing for now.

**Comment by TomasVotruba** [comment]
Just a random thought, I've used `DataProvider` instead of array in the `test*` method and I found out it calls `setUp()` for each item.

I had test container initialized in there, so it take ~5 s instead of 200 ms as before.

Maybe the `setUp()` and deeper is place to look at.

I fixed it like this: https://github.com/Symplify/Symplify/commit/6fef9dae99ef34b6c8c48f3a3485e84aec65ae7f
