### ISSUE TITLE
HttpSmokeTestCase::testHttpResponse - Using $this when not in object context

### ISSUE THREAD

**Issue by wuestkamp** [shopsys/shopsys#526]
I did upgrade an application from Symfony 2.8 to 3.4. When I now run the Smoke Tests **in process isolation** I get the following error:

```
386) App\Bundle\AppBundle\Tests\Functional\SmokeTest::testHttpResponse with data set #385 (Shopsys\HttpSmokeTesting\RequestDataSet Object (...))
PHPUnit_Framework_Exception: PHP Fatal error:  Using $this when not in object context in /project/var/cache/test/ContainerU02p1kx/getRouting_LoaderService.php on line 8
Fatal error: Using $this when not in object context in /project/var/cache/test/ContainerU02p1kx/getRouting_LoaderService.php on line 8
```

All 386 errors are the same. Any idea what could cause this?

Using version v1.1.0 of "shopsys/http-smoke-testing"

Thanks a lot,
Kim

**Comment by wuestkamp** [comment]
I removed all phpunit references via composer, then installed "symfony/phpunit-bridge" and run smoke tests via `./bin/simple-phpunit` and this error disappears.

**Comment by PetrHeinz** [comment]
Hi @wuestkamp and thanks for reporting this.

Using `phpunit-bringe` instead of `phpunit` was already suggested in #380, but I'm not sure about all the pros and cons... We definitely want to keep the package compatible with older applications, as HTTP smoke testing approach can provide huge benefits to legacy apps that have no other means of automated testing.
