### ISSUE TITLE
monorepo-tools: Duplicate commit messages, with non-existent commit hashes

### ISSUE THREAD

**Issue by dandv** [shopsys/shopsys#572]
### What is happening
Has anyone else noticed duplicate commit messages in the log? I saw quite a few of these when bringing together 6 repos (unfortunately I can't share the code). One of the commits had a hash I couldn't find in the original repo.

[tomono](https://github.com/unravelin/tomono) didn't have this problem (used with the same repos).

**Comment by PetrHeinz** [comment]
Hi @dandv and thanks for reporting. Have the original commits in question been signed (eg. created in GitHub web UI) by any chance? If so, it is unfortunately a known behavior, please see #435 and #445. If that's not your case, please, provide as much info as you can, otherwise it would be impossible to pin down.
