### ISSUE TITLE
Operator information page should be visible for singledomain

### ISSUE THREAD

**Issue by henzigo** [shopsys/shopsys#599]
### What is happening

Page Operator information is not visible in side menu bar for singledomain, but i can go to this page (admin_shopinfo_setting) by type url.

### Expected result

Operator information should be visible in menu for singledomain.

**Comment by PetrHeinz** [comment]
Thanks @henzigo for reporting.

The issue was introduced during redesign of administration in #244, by adding *Operator information* to multidomain-only menu item *E-shop identification*.

Before:
https://github.com/shopsys/shopsys/blob/34579a7a83fc8230364c74ac37366eb473696579/packages/framework/src/Resources/config/admin_menu.yml#L126-L140
After:
https://github.com/shopsys/shopsys/blob/bc0bcb60d9d6d7aac4d7d658b79b5409752a9842/packages/framework/src/Resources/config/admin_menu.yml#L126-L136
