### ISSUE TITLE
How to Upgrade to the new version of Shopsys Framework

### ISSUE THREAD

**Issue by Miroslav-Stopka** [shopsys/shopsys#653]
Hi, we run into some problems during UPGRADE preparations. Can you help us please?

### What is happening
1) We are preparing for the upgrade to the version _beta4_. 

2) Our project is on the version beta2 right now and we are trying to estimate, how long it will take to upgrade to the beta4 version. We have already implemented approximately 100-150hours of individual modifications on project base. 

3) We are aware of  `UPGRADE.md` file

4) Are there any tutorials or recommendations on how to upgrade?

5) What about this scenario:
- class `Shopsys\FrameworkBundle\Component\Localization\DateTimeFormatPatternRepository`
 has on the version beta2 method `private function isMatching(...) `
- we have created the child of this service `DateTimeFormatPatternRepository` and we needed to use this method `isMatching()` so we copied this method into our child (because of inability to use parent private method)
- in the version beta4 this method of `Shopsys\FrameworkBundle\Component\Localization\DateTimeFormatPatternRepository` can be changed  to protected so if we would create a child after the upgrade, there would be no need for a copy of this method (because we are able to use parent protected method)
- question is, what should we do now after upgrade to beta4? Shall we remove the copied method and shall we use the parent one? Or can we ignore it? 
- try to imagine that this scenario can be relevant to the thousands of individual modifications, what do you suggest?

6) Is there any way to find out which "copied methods" are no longer needed and can be replaced by parent call? 

7) Do the `UPGRADE.md `contains information about all changed visibility of methods and properties?

8) How did you try to solve the scenario from the point 5) while upgrading your demo shop?

### Expected result
a) Answered questions 1-8
b) Available some tutorials or recommendations about how to upgrade

**Comment by Miroslav-Stopka** [comment]
I thought it should be possible to create a checker to check if the child does not override a protected or public parent method. This checker could be implemented as a phing target and at least it could inform the project developer about which methods (copied methods) can be replaced by parent method call :) What do you think?

**Comment by vitek-rostislav** [comment]
Hi, I am thinking of https://github.com/rectorphp/rector, what do you say, @TomasVotruba? :thinking: :slightly_smiling_face:

**Comment by TomasVotruba** [comment]
@vitek-rostislav Hey, I don't think it's worth to invest time to lear + keep rector sets for Shopsys until the stable is out. But then it's a must have for PHP code :+1:

**Comment by Miroslav-Stopka** [comment]
Hi @vitek-rostislav, and what about the others questions?

**Comment by vitek-rostislav** [comment]
Hi @Miroslav-Stopka.

All the recommendations and instruction for upgrading are located in the mentioned `UPGRADE.md`. 

According to experience from upgrading demo shop - we have just started to work on it today, so please be patient a little bit more. We are already aware that the instructions are not optimal, eg. instructions for modifying `docker-compose.yml` are there multiple times...We want to improve the instructions based on our as well as your experience from upgrading.

>question is, what should we do now after upgrade to beta4? Shall we remove the copied method and shall we use the parent one? Or can we ignore it?

If the content of your copied method is the same as the parent one, I would remove the method as it is not necessary anymore. However, I see that it is a problem to find all such methods - it is a good idea to have some tool for that, we can try to do some research or implement it ourselves.

>Do the UPGRADE.md contains information about all changed visibility of methods and properties?
Well, it should IMHO, however, it does not at the moment. The question is, whether this would be helpful for you? Or would it be sufficient for you like that - https://github.com/shopsys/shopsys/blame/master/UPGRADE.md#L325?

**Comment by MattCzerner** [comment]
Hi, first of all, you demand answers to 8 questions, but i see 4 questions (4,6,7 and 8).

All these are my personal opinions but i will try to answer each of them.

4) `UPGRADE.md` file which explains how to upgrade to a newer version, Im not sure what do you imagine.. In my opinion `UPGRADE.md` should be enough for people to upgrade (I am not saying that this is the state now, we know that the instructions are not optimal)

6) No. The thing that would help in this scenario is the BC promise that is in work. BC promise says if there will be added methods, or changed and when, and most importantly in which kind of versions you might expect this to happen. So for example if our BC promise will say, we are not changing any methods in minor versions, you can be certain that your current scenario 5 will not happen, on the other hand, if you would be upgrading to major version, you would read in our BC promise that we can change methods, and those changes would be expected and easy to find. Because they will be in `UPGRADE.md` file.

7) Most likely not. We are just learning to write this correctly.

8) Well, there is not a bad scenario in this one for me, you can use your method, if you do not believe framework to keep this method untouched, or you can delete it and use framework's one.

Look, all these questions has something in common and that is missing BC promise and the fact that SSFW is in beta version. Ideal state would be to have stable version, where with BC promise there is marked classes and methods, that will not be changed, that way, if we decide to make any change in these methods, they will be added into next major release. By adding them to next major release, you will expect these kinds of changes when upgrading to major version. (This is just an example and it could not be like that in the end)

For example, look at the `[Symfony BC promise]https://symfony.com/doc/current/contributing/code/bc.html)`.

For now, the best way to solve this is to keep tranfesring experiences from upgrading for us to improve and make most of BC breaks as soon as possible before stable release, so we can make our promise as strict as possible for you to be sure what to expect when upgrading.

**Comment by vitek-rostislav** [comment]
As I mentioned before, we are working on the demoshop upgrade currently, I am linking here the PR as it might be useful for you :slightly_smiling_face: https://github.com/shopsys/demoshop/pull/27

**Comment by Miroslav-Stopka** [comment]
Thank you @vitek-rostislav, glad to hear that, we are waiting for the results of the demoshop upgrade :)

I have already consulted the question about "optional" tags with @grossmannmartin. He applied all optional actions from UPGRADE.md as well :) So this is the helpful answer 🎆to one of my questions connected to the upgrade: what about optional tags. Thank you.

**Comment by grossmannmartin** [comment]
Hi, if you're planning upgrade to beta3, there is one caveat, that can be easily missed.
If you use your own data fixtures, please pay special attention to shopsys/shopsys#568.

Here we replace own fixtures loader command with standard doctrine fixtures. As a result, your data fixtures can be loaded first and rewritten with the default frameworks afterward.

One of the options, how to fix this is to "untag" framework data fixtures and they will not be processed at all. You can see, how we fixed it on demoshop shopsys/demoshop@f86cf2dc2a028dbf2f5fa0e81ccec0954958c499

**Comment by TomasVotruba** [comment]
@vitek-rostislav I've just noticed many class-renames like: https://github.com/shopsys/shopsys/compare/v7.0.0-beta4...master#diff-fbab69f8a4c3942afdbfee7cfe8b77c3
This means people have to rename classes in ctors, in typehints, in parents classes. Uff. Such work can be delegated to Rector actually, even before going to stable.

**Comment by vitek-rostislav** [comment]
Hi @Miroslav-Stopka, I would like to close this issue as it seems to me that everything is solved for now, what do you say?

We are not in beta anymore and there is a [BC promise](https://github.com/shopsys/shopsys/blob/v7.0.0/docs/contributing/backward-compatibility-promise.md) so you can be sure what kind of changes can be expected in each release. Also, we are constantly improving the upgrading notes based on your feedback and based on our own experience from upgrading demoshop (e.g. https://github.com/shopsys/demoshop/pull/37 followed by https://github.com/shopsys/shopsys/pull/868). The *optional* tag in release notes is not used anymore, we use *low-priority* now and its purpose is described in [general upgrading instructions](https://github.com/shopsys/shopsys/blob/v7.0.0/UPGRADE.md).

The scenario you described in the issue description (bullet 5) is not likely to happen now and if so, you should be warned by PHP itself - when you overwrite a private method and it becomes protected in the parent, you get a fatal error as you are not allowed to overwrite access level this way (from protected to private). Moreover, all properties and metods in `Model`, `Controller`, and `Component` namespaces have `public` or `protected` vsibility now - `private` visibility is not allowed and we have even a fixer for that (see `ForbiddenPrivateVisibilityFixer`).

**Comment by Miroslav-Stopka** [comment]
Hi @vitek-rostislav,

agree, the problems described in this issue have been clarified and the solutions have been implemented as well.

Thank you 👏
