### ISSUE TITLE
User::ChangeMail() does not check a domain

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#661]
### What is happening

This description reflects changes done on https://github.com/shopsys/shopsys/pull/627.
`User::changeEmail()` does not take into account domain of given `$userByEmail` parameter. Therefore, it could throw `DuplicateEmailException` even when the passed user is from the other domain than the one whos email is edited.

### Expected result

`User::changeEmail()` should containt the same domain check the is in `UserFactory::create()`

**Comment by simara-svatopluk** [comment]
@vitek-rostislav 
What I should do is duplicate checking logic in `UserFactory`, but I'm depressed when I have to duplicate something.... So I'm thinking and have couple of suggestions:

* create static checking method on `User`
* create `DuplicateEmailChecker` that will have no constructor and will be used like `(new DuplicateEmailChecker())->check($userByEmail, $userData)`
* the same as previous, but static
* move the checking logic to constructor of `User`, so constructor can call protected method `checkDuplicateEmail` and changeEmail can call the same protected method. But this is quite most BC-break, because it changes constructor

Which way do You prefer? Or duplicating code?

**Comment by vitek-rostislav** [comment]
Hi, good point. Duplicating the logic is not a good idea :+1: 

I like almost all of your suggestions :smile: 

If I should vote, I would probably go with static method in `User` :slightly_smiling_face:

**Comment by simara-svatopluk** [comment]
If it was only up to me, I would pick `User` constructor, 2nd choise would be nonstatic `DuplicateEmailChecker`, third static method in `User`

**Comment by simara-svatopluk** [comment]
constructor
