### ISSUE TITLE
Choosing a type for price representation and calculation

### ISSUE THREAD

**Issue by PetrHeinz** [shopsys/shopsys#745]
### What is happening

At the moment, we are using a mix of `string`, `int` and `float` types when dealing with monetary values. This leads to problems with type-hinting (see #683 and #288), comparing two values (eg. `0.1 + 0.2 === 0.3` produces `false` in PHP) and rounding errors, which may get out of hand when a lot of different calculations are compounded (eg. applying a lot of coefficients to a price).

This may lead to prices being off by a cent or to hard-to-debug issues.

I have found 6 different approaches that we could take and I've described them below with their pros and cons. I'd like to hear your opinion on what should get implemented.

1) We will just use floats.
2) We will cast numbers to strings when passing the values to another method.
3) We will implement a custom value-object.
4) We will use a library for Decimal type.
5) We will use [a PHP extension](http://php-decimal.io/) for Decimal type.
6) We will use the [Money pattern](https://martinfowler.com/eaaCatalog/money.html) (using a library).

**The options are described below in separate comments - please use reactions :+1: and :-1: to express your opinion and add a comment to share your thoughts. Thanks!**

**We would like to come to a final decision on Thursday 24th, so we have a week to discuss this.**

If you find another possible approach you'd like to propose, feel free to add one in a separate comment, preferably in the same format as one of the six. :slightly_smiling_face: 

### Expected result

Decision is made about how we will represent and calculate prices (at least in the first release after we leave beta). After the changes are implemented, type-hints are consistent (will close #683, #288). Users will have a documented way to upgrade to this state.

Moreover, all no non-strict comparisons like these will be replaced by their strict counterparts:

https://github.com/shopsys/shopsys/blob/2abf7e410a322f97a909f5c4fc03728bd49e64d5/packages/framework/src/Model/Cart/Watcher/CartWatcher.php#L52
https://github.com/shopsys/shopsys/blob/2abf7e410a322f97a909f5c4fc03728bd49e64d5/packages/framework/src/Model/Order/Watcher/TransportAndPaymentWatcher.php#L117
https://github.com/shopsys/shopsys/blob/2abf7e410a322f97a909f5c4fc03728bd49e64d5/packages/framework/src/Twig/PriceExtension.php#L155
https://github.com/shopsys/shopsys/blob/2abf7e410a322f97a909f5c4fc03728bd49e64d5/packages/framework/src/Twig/PriceExtension.php#L170

**Comment by PetrHeinz** [comment]
Personally, I'd like to implement the Money pattern (6), but it seems like a massive change, that would be hard to implement and hard to upgrade to. Being at the end of the beta phase, I would rather avoid such a BC-break.

Using floats (1) or strings (2) seem like the easiest options, but they do have big problems with accuracy and comparisons. Using them in e-commerce projects for handling monetary values might lead to unexpected issues. Even though I can say I'd prefer using strings, I would rather choose some other option.

From my experience I'd like to avoid reinventing the wheel by custom implementation (3), as it would lead to much effort being spent on already solved issues. I'd rather use some kind of a standard solution.

This train of thought leaves us with 2 options - either use a Decimal class using the [litipk/php-bignumbers](https://github.com/litipk/php-bignumbers) library (4) or the [php-decimal](http://php-decimal.io/) extension (5). Because of the easier usage, less changes to codebase and the fact that we can add and configure a PHP extension pretty easily in Docker images, **I'd prefer the option 5**.

**Comment by PetrHeinz** [comment]
**1. We will just use floats.**

**Comment by PetrHeinz** [comment]
**1. We will cast numbers to strings when passing the values to another method.**

**Comment by PetrHeinz** [comment]
**3. We will implement a custom value-object.**

**Comment by PetrHeinz** [comment]
**4. We will use a library for Decimal type.**

**Comment by PetrHeinz** [comment]
**5. We will use a PHP extension for Decimal type.**

**Comment by LukasHeinz** [comment]
**We will just use floats.**
We are doing SSFW for big e-commerce projects and preciseish in pricing is not good enough.
**We will cast numbers to strings when passing the values to another method.**
Same as above - can cause problem in crucial part of SSFW.
**We will implement a custom value-object.**
Please do not reinvent the wheel
**We will use a library for Decimal type.**
Kind of easy solution using quite reliable library (105 stars, 200k installs)
**We will use [a PHP extension](http://php-decimal.io/) for Decimal type.**
The extention is here for 3 months and it was downloaded 310 times. I do not belive this much.
**We will use the [Money pattern](https://martinfowler.com/eaaCatalog/money.html) (using a library).**
Most difficult but seems that will bring best solution. It is operational one year and it has 2M downloads. Can handle bitcoin and other crazy edge cases.

For me only viable option if we want to resolve situation about prices is usage of Decimal library or Money pattern library. And i would prefer Money pattern

**Comment by pk16011990** [comment]
This issue is only about price, but I have more general problems with floating point. For example stock quantities in decimal numbers (it is not implemented in SSFW stable, but It is not rare in eshops).

And option no. 6 Money pattern is not useable for another decimal numbers (for prevent to floating point problem). Or is there solution for work with general decimal numbers (not just money) in Money pattern? I did not study all about Money pattern...

**Comment by PetrHeinz** [comment]
@pk16011990: It's true that the Money pattern does not solve the issue of floating point precision in general, thanks for pointing that out. The prices are the most important use-case, but we'll need to use either floats, casting to strings or the Decimal class for the other uses of decimal numbers.

I would prefer using either casting to strings (I see it as a better fit than floats) or Decimal using a library (as it's more reliable than the extension, as @LukasHeinz mentioned).

**Comment by vitek-rostislav** [comment]
Hi @PetrHeinz, thanks for the excellent preparation! :ok_hand: :heart: 

My train of thought is very similar to yours. I liked the Money type until @pk16011990 mentioned it does not solve the other common use-cases/problems with floats.

The best solution for me is using Decimal, I would prefer the extension way as I really do not like that massive performance decrease caused by the library :slightly_smiling_face:

**Comment by grossmannmartin** [comment]
Although I see the problem with decimal numbers in general, please keep the scope of this issue.

**Money pattern**
Personally, I believe the Money pattern is the best choice, but I agree it would be hard to implement. 
Hard to upgrade probably too, but if we consider this type of change, we have to do it now. In any later stage of a product, it will be nearly impossible.

**PHP extension**
A looked at php extension and seems a bit odd to me. Extension raise warning on data loss (parsing with lower precision). I don't like warnings - its harder to work with them in the application (see http://php-decimal.io/#basic-usage). 

And comparing seems a bit odd. Two Decimal objects are equal if their numeric values are equal, *as well as their precision.* 

But I don't think the age of the package or the number of downloads is a limiting factor. It looks just like a simple wrapper around libmpdec library – And this is the basis for Python’s decimal module since Python v3.3).

**Comment by henzigo** [comment]
@PetrHeinz, @pk16011990 Probably decimal type will be added to money pattern in next version. See https://github.com/moneyphp/money/pull/516

Personally money pattern is the best choice for me and we would be able to use decimal extension for prevent other problems with floats.

**Comment by simara-svatopluk** [comment]
This issue is about prices. I understand that you want to fix more issues, but when we loose focus, then we'll fix nothing. **So I will arrogantly ignore anything that is not related to price issue.**

1. Floats - No - floats doesn't fulfill money use cases
2. Strings - NO - this is even crazier that floats
3. Custom value object - No - reinventing wheel
4. **Decimal Type - Yes** - we are using prices as decimals in SSFW, we don't care about currency when working with prices. So this approach matches our use-cases best
5. Extension - No - hard to change, we don't use this approach in SSFW, we use libraries
6. **Money Type - Possible** - It is the best choice for working with prices. But in SSFW we have different use-cases - we don't care about currency, but his library forces us to work with currencies. So the match is not perfect

7. **I prefer to create our own `Money` object that will use internally solution 4 or 6. It would only delegate the responsibility. Our custom `Money` object will fit our use-cases best and will provide us flexibility to change the used library if our needs changes in the future.**

**Comment by PetrHeinz** [comment]
To summarize the discussion, due to overwhelming negative feedback on using primitives (1, 2) or implementing a custom solution (3) the only relevant options are:

**4) We will use [litipk/php-bignumbers library](https://github.com/Litipk/php-bignumbers) for Decimal type.**
There are concerns about the performance impact of implementing the library. Otherwise, such a class matches our use of decimal numbers in pricing.

**5) We will use [php-decimal extension](http://php-decimal.io/) for Decimal type.**
There are concerns about the reliability and maturity of the extension. Also, some issues with the ease of use and flexibility were brought up (https://github.com/shopsys/shopsys/issues/745#issuecomment-454831111, https://github.com/shopsys/shopsys/issues/745#issuecomment-455455605).

**6) We will use the [Money pattern](https://martinfowler.com/eaaCatalog/money.html) (using [moneyphp/money library](https://github.com/moneyphp/money)).**
Even though it does not help with precision arithmetic in general (https://github.com/shopsys/shopsys/issues/745#issuecomment-454742363), it is seen as the best choice to be used as a type for prices. It might be hard to implement with the current state of pricing in Shopsys Framework.

We might introduce a wrapper object to delegate the responsibility. This would provide us with the possibility to change the implementation entirely without impacting the users (for a price of performance decrease and maintaining such a class, of course).

**Comment by simara-svatopluk** [comment]
@PetrHeinz I implemented wrapper object recently in my DDD demonstration project - https://github.com/simara-svatopluk/cart/blob/master/src/Domain/Price.php , https://github.com/simara-svatopluk/cart/blob/master/tests/Domain/PriceTest.php

And it's great, because libraries don't force you to have their interface. You have the interface that suits you the best. Eg. Money library forces you to use cents everywhere (you cannot have 15.5 crowns, you have to have 1500 hellers everywhere).

So if I can summarize my experiences, the easiest and most flexible will be custom object + 4-decimal

**Comment by PetrHeinz** [comment]
So after a long internal debate, particularly with @simara-svatopluk we have come to a conclusion.

Even though the Money type seems like a superior concept and adopting it would help avoiding some issues currently found in pricing, it would be much harder to implement. We would like to get to implementing Money type eventually, but in iterative steps.

**First, we'd like to address only the issue of types (and type-hints) of monetary values.**

**The Decimal type is the closes match for the use cases found in Shopsys Framework. Prices are always just decimal numbers, not being always tied to a currency. Implementing the Decimal type seems like a natural step.** We will rather use the library than the extension because of reasons explained above (https://github.com/shopsys/shopsys/issues/745#issuecomment-454831111, https://github.com/shopsys/shopsys/issues/745#issuecomment-455455605, https://github.com/shopsys/shopsys/issues/745#issuecomment-457514485).

To ease changes in the future (especially in the direction of implementing Money type), we will implement a custom wrapper class `Money` (alternatively `MonetaryDecimal`, `DecimalMoney`, `MoneyAmount` or something along those lines). This wrapper will be then used to represent all monetary values in Shopsys Framework just as they are represented now by `int`/`string`/`float`. A custom Doctrine type will exist, basically copying `\Doctrine\DBAL\Types\DecimalType`, but converting to/from the instances of our wrapper class. A form data transformer will exist to help with form fields (basically just the `\Symfony\Component\Form\Extension\Core\Type\MoneyType`).

The wrapper class will also be used to reduce available methods (there is no need for square roots in e-commerce) or rename them (eg. `multiply` instead of `mul`). All arithmetic operations and comparisons will be done using a method call. There will be no `__toString` method so we avoid unintentional casting.

As much as possible of the current logic and structure will remain the same. Eg. the `Rounding` class will still round prices (represented by the new wrapper class) without VAT and VAT amounts to 2 decimal numbers and the price with VAT to either integers, halves or hundredths.

Only that will be removed are those that were implemented to bypass the floating point errors, eg.:
https://github.com/shopsys/shopsys/blob/5174c8fa54dc03f89ac4380110c1c5e35b5223c2/packages/framework/src/Twig/PriceExtension.php#L243-L245

**Comment by PetrHeinz** [comment]
@TomasLudvik The maturity, documentation and adoption of the mentioned extension felt like a big disadvantage. The advantages of the extension were a bit diminished by the planned wrapper class we want to implement for easier path to Money type adoption - performance would be a bit decreased by the object usage and ease-of-use would be removed altogether, as the wrapped would not support the arithmetic operators etc.

While I don't have any final comparison between the Decimal extension and library, I did a quick performance test of the Decimal library with these results (from which the claim about the hundredfold performance decrease originates):

|  | primitives | `Litipk\BigNumbers\Decimal` | custom wrapper around `Decimal` |
| --- | --- | --- | --- |
|  | plain floats and integers | using Decimal with unspecified scale* | using Decimal with scale of 32 internally |
| calculations | 0.00133 s | 0.17511 s | 0.15651 s |
| object instantiation | 0 s | 0.02697 s | 0.03540 s |
| total | 0.00133 s | 0.20208 s | 0.19191 s |

The tested calculations were of this sort:
- (3263 + 1124) / 950 * 14
- (3737 + 2407) / 446 * 98.55
- (795 - 6916) / 441 * 78.18

and there were 10 thousand of them to take the times cited above on my local machine.

You can re-run the test yourself or try other approaches to assess the performance [in `DecimalTestCommand` in my prototyping branch `ph-decimal-prototype`](https://github.com/shopsys/shopsys/blob/6c251d2da272b817d65f3d57a767fb35b40713b6/packages/framework/src/Command/DecimalTestCommand.php).

\* - *The unspecified scale caused rounding errors because of `Decimal::fromInteger()` results in scale being 0 and the auto-scaling of division is only "reasonably" precise. This can be avoided in the real implementation, especially with the wrapper class.*

Even though the performance is 100&times; lower, for e-commerce related use cases it should be fast enough, in my opinion. The other factors out-weighted the decision in favor of the library.
