### ISSUE TITLE
Configuration for domains should not be tracked with git

### ISSUE THREAD

**Issue by grossmannmartin** [shopsys/shopsys#804]
### What is happening
When I want to make some changes to domains for testing purposes, changes in `domains.yml` file are tracked with git and I can easily push unwanted change to the repository.

And when I build own singledomain project on based on project-base, behavior is even stranger. 
I change `domains.yml` (to have only one domain), and push this file, but then I need either to change `domain_urls.yml.dist` or make adjustments manually on deploy. 

### Expected result
Default implementation should be in tracked file `domains.yml.dist`, and file `domains.yml` should be ignored by git. Behavior should be the same as domains_urls.

**Comment by PetrHeinz** [comment]
This is actually intentional. Domain setting `domains.yml` is very important for projects so it makes sense to be shared among its developers (hence it should be commited into the repository just as you commit changes to demo data fixtures).

On the other hand, domain URLs setting is something that is different on every machine, based on the way it's installed and run.

You should either be careful about what files your track and commit or you can overwrite the parameter `shopsys.domain_config_filepath` in your uncommited `parameters.yml` to some untracked file (or even a file outside the repository).

**Comment by simara-svatopluk** [comment]
@grossmannmartin Is Petr's explanation enough to close your issue?

**Comment by grossmannmartin** [comment]
Indeed it is. Thanks, both of you, closing the issue now.
