### ISSUE TITLE
Constants are not extendable

### ISSUE THREAD

**Issue by MattCzerner** [shopsys/shopsys#827]
There is no possible solution to changing value of constants from framework which is relevant use case.

### What is happening
I think best to describe is an example.

This is a real class from framework
```
<?php

namespace Shopsys\FrameworkBundle\Model\Product\BestsellingProduct;

class BestsellingProductFacade
{
    const MAX_RESULTS = 10;

    ...
}
```
If I would like to change value of `MAX_RESULTS` to  for example 20, from Shopbundle, i got no way to do that in a nice way.

### Expected result
I think of 2 solutions that could be implemented.

1) Use static constants, in which case we can enable chaning of values from ShopBundle by standard overriding of constant in your implementation.

2) Use `get()` for constants. In which case you can simply inject your own constant into getter

I would prefer first solution.

**Comment by boris-brtan** [comment]
self([:]{2}[A-Z_0-9]+) -> static::\1

**Comment by PetrHeinz** [comment]
`static` can only be used from inside of the class so it's a viable solution only for protected constants...

By using `get()` you mean writing getter methods instead of using constants?

If it's meant to be configurable and changed, why not use a parameter injected into the constructor from DIC configuration instead? See #806 for an example.

**Comment by grossmannmartin** [comment]
`self` can be used also only from inside of a class, isn't?

I believe the main problem lies in code like this:

```php
class A {
    protected const MAX_RESULTS = 10;

    public function printLines()
    {
        printf('printing %d results', self::MAX_RESULTS);
        echo "\n";
    }
}

class B extends A{
    protected const MAX_RESULTS = 20;
}

(new B())->printLines(); // printing 10 results
```

But I agree, it doesn't cover situations when you use `A::MAX_RESULTS` outside of a class.

**Comment by PetrHeinz** [comment]
@grossmannmartin Yes, my point is that using `static` instead of `self` can reliably resolve this issue only for constants that are used only inside of that class (and we know that for sure only about protected constants). I should have made myself clear by providing an example.

**Comment by simara-svatopluk** [comment]
I agree with @PetrHeinz, if there is need to change these values, these values are not constants anymore. And I also prefer constructor injection, so anyone can easily change these values in the project

**Comment by grossmannmartin** [comment]
Well I understand constant as something that cannot be changed during normal code execution. I don’t see why it shouldn’t be overridden. 
But cannot argue with constructor injection 👌

This issue, as I understand it, was about quick way to fix certain use case. Constructor injection is better solution but also not so easy to do.

**Comment by simara-svatopluk** [comment]
@grossmannmartin sorry, I'm confused by your response.
> constant as something that cannot be changed

constants = no change
> I don’t see why it shouldn’t be overridden

constants = can be overridden (so changed)

Maybe it's just because of the double negation, but I'm just confused.... what do you mean? Because two previous statements are in contradiction for me.

**Comment by grossmannmartin** [comment]
@simara-svatopluk I meant they cannot be changed by the code itself. I can't change their value directly depending on some condition for example.

I may not use the proper terms, because I don't "override" the constant.
I can extend the class and create constant with the same name (in a different class). 

But there always will be `A::MAX_RESULTS` as well as `B::MAX_RESULTS` (example code above).

It's the *usage of the constant* related to late static binding that should be revised in the scope of this issue.
