### ISSUE TITLE
EntityExtensionTest:entityExtensionMap

### ISSUE THREAD

**Issue by Miroslav-Stopka** [shopsys/shopsys#843]
Hi my friends :),

I'm a little confused with your EntityExtensionTest. 

### What is happening
1. I created the extension of Availability entity in ShopBundle 
2. Functional tests start to fail :(
```
PHP Warning:  Uncaught Symfony\Component\Debug\Exception\ContextErrorException: Warning: require(/var/www/html/var/cache/test/doctrine/orm/Proxies/__CG__ShopsysFrameworkBundleModelProductAvailabilityAvailability.php): failed to open stream: No such file or directory in /var/www/html/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php:206
Stack trace:
#0 /var/www/html/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php(206): require()
#1 /var/www/html/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php(116): Doctrine\Common\Proxy\AbstractProxyFactory->getProxyDefinition('Shopsys\\Framewo...')
#2 /var/www/html/vendor/shopsys/doctrine-orm/lib/Doctrine/ORM/UnitOfWork.php(2789): Doctrine\Common\Proxy\AbstractProxyFactory->getProxy('Shopsys\\Framewo...', Array)
#3 /var/www/html/vendor/shopsys/doctrine-orm/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php(271): Doctrine\ORM\UnitOfWork->createEntity('Tests\\ShopBundl...', Array, Array)
#4 /var/www/html/vendor/s in /var/www/html/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php on line 206
PHP Fatal error:  Doctrine\Common\Proxy\AbstractProxyFactory::getProxyDefinition(): Failed opening required '/var/www/html/var/cache/test/doctrine/orm/Proxies/__CG__ShopsysFrameworkBundleModelProductAvailabilityAvailability.php' (include_path='/var/www/html/vendor/phing/phing/classes:.:/usr/local/lib/php') in /var/www/html/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php on line 206
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalErrorException: Compile Error: Doctrine\Common\Proxy\AbstractProxyFactory::getProxyDefinition(): Failed opening required '/var/www/html/var/cache/test/doctrine/orm/Proxies/__CG__ShopsysFrameworkBundleModelProductAvailabilityAvailability.php' (include_path='/var/www/html/vendor/phing/phing/classes:.:/usr/local/lib/php') in /var/www/html/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php:206
Stack trace:
#0 {main}

Next Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The "kernel" service is synthetic, it needs to be set at boot time before it can be used. in /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:334
Stack trace:
#0 /var/www/html/var/cache/test/ContainerNupreia/appTestProjectContainer.php(5479): Symfony\Component\DependencyInjection\Container->get('kernel', 1)
#1 /var/www/html/var/cache/test/Con
```
3. Debugging....
4. Debugging....
5. Finding out that the problem is in the EntityExtensionTest
6. Debugging....
7. Debugging....
8. Just random experiment with adding new item into $entityExtensionMap 
```
Availability::class => ExtendedAvailability::class,
```
9. Tests pass successfully
10. Confusion

Questions:

- Why there exists this array $entityExtensionMap? Is it not confusing that entity extension map exists in parameters_common but this map is ignored in this test?

- I could understand to this form if EntityExtension/Model would contain ExtendedAvailabilty.php. But such a file does not exist. So why do I need to add this new item into this $entityExtensionMap?

- A couple of weeks back we created extension of Flag entity and the modification of  $entityExtensionMap array was not needed. Are there some rules, when it is neccessary to extend this $entityExtensionMap array?

### Expected result
- Described the usage of $entityExtensionMap array in EntityExtensionTest
- Answered my questions :D

Thank you

**Comment by simara-svatopluk** [comment]
> Why there exists this array $entityExtensionMap? Is it not confusing that entity extension map exists in parameters_common but this map is ignored in this test?

Yes it is ignored. The test `EntityExtensionTest` sets its own environment - it has own entities and tests these entities.

> I could understand to this form if EntityExtension/Model would contain ExtendedAvailabilty.php. But such a file does not exist. So why do I need to add this new item into this $entityExtensionMap?

I have no idea why this problem occurs, because the test should have own environment, so working with extended entities in the system should not influence the test. This seem like a bug for me.

> A couple of weeks back we created extension of Flag entity and the modification of  $entityExtensionMap array was not needed. Are there some rules, when it is neccessary to extend this $entityExtensionMap array?

This is correct behavior. If you extend a class, you shouldn't be forced to change the test.

**Comment by simara-svatopluk** [comment]
And you just run into an interesting problem - you have tests in `project-base` that are not yours and you have to maintain them. Long-term solution is moving functional tests into the `framework`.

But it is just a note, we're not going to move functional tests soon.

**Comment by Miroslav-Stopka** [comment]
Hi @simara-svatopluk,

thank you for your response about mentioned problem :)

And the fact that tests stand out as the part of project-base, is perfectly OK with me :) We are happy that we can modify them as we please. Actually, none of my team colleagues ever objected about this state :) 

Maybe some discussion with the community can be helpful.

**Comment by simara-svatopluk** [comment]
Well, we can discuss even here as your issue is related with tests.

Let's take one example from functional tests: [`DomainsConfigLoaderTest`](https://github.com/shopsys/shopsys/blob/master/project-base/tests/ShopBundle/Functional/Component/Domain/Config/DomainsConfigLoaderTest.php)
Do you see any value in running this tests every time you are building your project?
Wouldn't it make more sense if this particular test was part of the `framework` package and you won't be forced to run it all the time?

**Comment by PetrHeinz** [comment]
@Miroslav-Stopka: The problem with this is that the tests have two responsibilities - they should help you as a user to develop your project faster and more reliably and at the same time they should help us to develop Shopsys Framework. This particular test is more of the later sort - it tests that the extensibility of entities work as intended. If you don't change the mechanics of entitiy extension, it may have only little value to you. Rewriting the test so it work well for both groups is not an easy task, that's why we'd like to move some functional tests out of the project-base and leave only those tests that are supposed to help project developers.

**Comment by Miroslav-Stopka** [comment]
@PetrHeinz, Im perfectly fine with splitting functional tests into two separated groups :) This is the first time you mentioned this solution. 

@simara-svatopluk DomainsConfigLoaderTest as part of framework package? Seems like a good idea. OrderFacadeTest as part of project-base? I agree on that as well.
