### ISSUE TITLE
E-mail attachment on CI

### ISSUE THREAD

**Issue by PetraPiprekova** [shopsys/shopsys#858]
### What is happening

When I upload an e-mail attachment to the e-mail templates and send the e-mail with the attachment, the e-mail is not delivered. (Reporetd by Partik Bajer)

### Expected result
Please fix it.

**Comment by boris-brtan** [comment]
#805

**Comment by Miroslav-Stopka** [comment]
Hi,

the main problem seems to be:

- Swift library runs with "/web" as document root

- UploadedFileLocator runs with "$projectDir" as document root

- paths.yml contains "shopsys.uploaded_file_dir: '/web%shopsys.uploaded_file_url_prefix%'"

- UploadedFileLocator checks in fileExists() path "/web/content/..../file.pdf", a and for this path, fileExists() returns true -  "$projectDir"+"/web/content/..../file.pdf" 

- then this path "/web/content/..../file.pdf" is through getMailTemplateAttachmentsFilepaths() of MailTemplateFacade returned as attachment path

- finnaly, Swift_ByteStream_FileByteStream tries to open this file on path "/web/content/..../file.pdf" but this action fails - because Swift_ByteStream_FileByteStream has "/web" as root and this class tries to open file on "/web" + "/web/content/..../file.pdf

**And?**

- if you will remove "/web" from "shopsys.uploaded_file_dir: '/web%shopsys.uploaded_file_url_prefix%'", Swift will work -- but UploadedFileLocator will be broken

- if you will not remove "/web" from "shopsys.uploaded_file_dir: '/web%shopsys.uploaded_file_url_prefix%'", UploadedFileLocator still works, but Swift is broken
