### ISSUE TITLE
Setting database_server_version should be out of parameters.yml.dist

### ISSUE THREAD

**Issue by pk16011990** [shopsys/shopsys#988]
File `parameters.yml.dist` should contain parameters that vary by instance (production, preproduction, local) not by project. However, it currently contains a Postgres version.

And I think that best practice is one project run only with one Postgres version. 

It is reason for move `database_server_version` from `parameters.yml.dist` into another file which is same for all instances of one project.
Who needs different versions can move it back.

BTW: Can not it be autodetected and cached during building of container?

**Comment by henzigo** [comment]
Hello, 
because of this issue #1002, it's not possible to autodetect database version, because it causes a problem in composer install, when is database not ready yet. After this issue will be solved, we can remove that parameter. For now, I moved `database_server_version` parameter to `parameters_common.yml`.

Thank you for reporting that.

**Comment by vitek-rostislav** [comment]
closed by #1001
